### ISSUE TITLE
New place to discuss the game

### ISSUE THREAD

**Issue by frowo** [frowo/Lucidteller#12]
I came back after a few days of inactivity, and noticed that there are no active threads, and the threads in the archive didn't even reach 100 replies before dying, the niche "community" we have is way too small to stay alive on an imageboard like 4chan, so we need to find a new place to keep discussions 
I was thinking something like riot.im/matrix, but i don't know if most people will be fine with having a username (I'm fine with it since I'm already technically a namefag in threads)

**Comment by frowo** [comment]
@VBPXKSMI what do you think?

**Comment by frowo** [comment]
created a matrix room just in case
#aidungeon2:matrix.org
https://matrix.to/#/!POQbaZhyalZxInIwwq:matrix.org?via=matrix.org

**Comment by AmoArt** [comment]
Yeah, I think one of the main problems would be difficulty to train a new specialised model since the original one was less than perfect and limited the way "AI" understood/presented the stories.
On unrelated note, I haven't touch AI Dungeon in forever, could someone explain to me how to use the word penalties?

**Comment by frowo** [comment]
@AmoArt pretty sure your post is in the wrong issue, but yes the model could be improved
For the word penalties, just check the config file, you add a word and a value, 5 discourages the word, 10 heavily discourages it, added a minus to encourage or heavily encourage

**Comment by frowo** [comment]
Another thread died with around 40 replies, I really think we need to start using Matrix/Riot

**Comment by VBPXKSMI** [comment]
@frowo Sorry for the delay, been away a few days and didn't see new threads on /vg/.
I find the matrix room idea is fine, I have already said it before in the past but this is what was going to happen once we got thrown on /vg/, so this is a necessary step.
Maybe becoming more active on 8kun on the /hg/ board could also be a solution, but we need to accept that this game will stay niche for quite some time, only thing that could gather more interest and people is by having an active develpment of the game (which is something I thank you for), I never really did anything to the game itself so I cannot help in this regard, aside from working on the Wiki.

Besides that, I spect to come back to continue working on the Wiki by the end of gebruary.

**Comment by frowo** [comment]
Riot room is now the place for most discussions, with maybe a few threads on boards like /vg/ and /tg/
