### ISSUE TITLE
Better option descriptions on config files.

### ISSUE THREAD

**Issue by pirone2** [frowo/Lucidteller#13]
We need better descriptions for all the variables you can adjust in the config file.
Some of it is really unintuitive, even for veterans like the different "gen-nums" and the way the penalties work with positive and negative values.

**Comment by frowo** [comment]
Yep, I have been thinking about the same thing for a long time, will be done soon

**Comment by frowo** [comment]
af0dd72012ba0fd2e25dc636c04881bc749f22dc fixed it
