### ISSUE TITLE
Save names for autosaves.

### ISSUE THREAD

**Issue by pirone2** [frowo/Lucidteller#14]
As of now, if you play with autosave turned on on the config, or turn it on while playing a new story, the game autosaves using that horrible ID system. Not only they are bad to remember/manage, it ends up creating lots of undesired save files.
To use a proper save name you have to manually save and choose a name, then load the save file, only then the autosave will work with the proper name.

A good fix for this would be the game asking you for a save name after generating the story, when it detects the setting turned on in the config, and using that instead of a random ID for that game. And forcing a manual save when turning autosave on via command, and making the game autosave to that name for the rest of that story instead of an ID.

**Comment by frowo** [comment]
will look into that later

**Comment by frowo** [comment]
afc22e93df71e5a1bda4b266a6cc6248487966f1 very quick fix, now autosaved stories will always be saved as "autosave", will be improved later so that you can choose the name you want

**Comment by frowo** [comment]
Done ee428d4f319e43d7da0400e1faf0a4c37ea63125
