### ISSUE TITLE
Weird spaces on most output linebreaks (FIXED BUT REQUIRES TESTING TO SEE IF FORMATTING IS BROKEN)

### ISSUE THREAD

**Issue by pirone2** [frowo/Lucidteller#9]
This issue in thadunge here:
thadunge2#86
is still present in this version.

**Comment by frowo** [comment]
Gonna try to find the reason for it

**Comment by frowo** [comment]
e069f4a655a5225d36b77f3912309ad1fc4ffe42
This has in my testing fixed the issue, however further testing is require, I'm gonna leave this issue open to see if anyone encounters a problem

**Comment by frowo** [comment]
no report of issues, closing it now
